file "motor.db"
{
  pattern
  {             P,     M,        DTYP,      PORT, ADDR,          DESC,  EGU, DIR, VMAX, VELO, VBAS, ACCL, BDST, BVEL, BACC,     MRES, PREC,DHLM,   DLLM, RTRY,   RDBD,  DLY, OFF, INIT }
  { MMC100:,  "m1", "asynMotor",  "MMC100",    0, "MMC100 sphi",   mm, Pos, 10.0,  0.5, 0.50,  0.2,    0,    1,   .2, 0.000001,    8,   5,     -5,    0, 0.000001, 0.05,   0,   "" }
}


file "asynRecord.db"
{
  pattern
  {          P,         R,      PORT,   ADDR,   OMAX, IMAX }
  {MMC100:asyn:,     sphi,    MMC100,      0,    256,  256 }
}


